cultura_general = [
    {"pregunta": "¿Cuál es la capital de Japón?", "correcta": "Tokio", "incorrecta": ["Osaka", "Kioto", "Nagoya"]},
    {"pregunta": "¿En qué continente se encuentra Egipto?", "correcta": "África", "incorrecta": ["Asia", "Europa", "Oceanía"]},
    {"pregunta": "¿Cuál es el río más largo del mundo?", "correcta": "Amazonas", "incorrecta": ["Nilo", "Yangtsé", "Misisipi"]},
    {"pregunta": "¿Qué moneda se utiliza en el Reino Unido?", "correcta": "Libra esterlina", "incorrecta": ["Euro", "Dólar", "Yen"]},
    {"pregunta": "¿Quién pintó la Mona Lisa?", "correcta": "Leonardo da Vinci", "incorrecta": ["Vincent van Gogh", "Pablo Picasso", "Claude Monet"]},
    {"pregunta": "¿En qué país se encuentra la Torre Eiffel?", "correcta": "Francia", "incorrecta": ["Italia", "España", "Alemania"]},
    {"pregunta": "¿Cuál es el idioma oficial de Brasil?", "correcta": "Portugués", "incorrecta": ["Español", "Francés", "Inglés"]},
    {"pregunta": "¿Qué planeta es conocido como el planeta rojo?", "correcta": "Marte", "incorrecta": ["Júpiter", "Saturno", "Venus"]},
    {"pregunta": "¿Cuál es el océano más grande del mundo?", "correcta": "Pacífico", "incorrecta": ["Atlántico", "Índico", "Ártico"]},
    {"pregunta": "¿Quién escribió 'Don Quijote de la Mancha'?", "correcta": "Miguel de Cervantes", "incorrecta": ["Gabriel García Márquez", "Jorge Luis Borges", "Mario Vargas Llosa"]},
    {"pregunta": "¿Cuántos continentes hay en el mundo?", "correcta": "7", "incorrecta": ["5", "6", "8"]},
    {"pregunta": "¿Cuál es el país más grande del mundo?", "correcta": "Rusia", "incorrecta": ["China", "Estados Unidos", "Canadá"]},
    {"pregunta": "¿Cuál es el metal más abundante en la corteza terrestre?", "correcta": "Aluminio", "incorrecta": ["Hierro", "Cobre", "Plata"]},
    {"pregunta": "¿Quién es el autor de 'La Odisea'?", "correcta": "Homero", "incorrecta": ["Sófocles", "Platón", "Aristóteles"]},
    {"pregunta": "¿Qué país tiene más habitantes?", "correcta": "China", "incorrecta": ["India", "Estados Unidos", "Indonesia"]},
    {"pregunta": "¿Cuál es el animal terrestre más rápido?", "correcta": "Guepardo", "incorrecta": ["León", "Tigre", "Lobo"]},
    {"pregunta": "¿Cuál es el desierto más grande del mundo?", "correcta": "Sahara", "incorrecta": ["Gobi", "Kalahari", "Atacama"]},
    {"pregunta": "¿Qué órgano del cuerpo humano produce la insulina?", "correcta": "Páncreas", "incorrecta": ["Hígado", "Riñón", "Estómago"]},
    {"pregunta": "¿En qué año cayó el muro de Berlín?", "correcta": "1989", "incorrecta": ["1991", "1987", "1993"]},
    {"pregunta": "¿Qué gas es esencial para la respiración?", "correcta": "Oxígeno", "incorrecta": ["Nitrógeno", "Dióxido de carbono", "Hidrógeno"]}
]

historia = [
    {"pregunta": "¿En qué año comenzó la Segunda Guerra Mundial?", "correcta": "1939", "incorrecta": ["1914", "1945", "1929"]},
    {"pregunta": "¿Quién fue el primer presidente de los Estados Unidos?", "correcta": "George Washington", "incorrecta": ["Abraham Lincoln", "Thomas Jefferson", "John Adams"]},
    {"pregunta": "¿Cuál fue el último faraón de Egipto?", "correcta": "Cleopatra", "incorrecta": ["Tutankamón", "Ramsés II", "Nefertiti"]},
    {"pregunta": "¿En qué año llegó Cristóbal Colón a América?", "correcta": "1492", "incorrecta": ["1500", "1485", "1495"]},
    {"pregunta": "¿Qué imperio construyó el Coliseo?", "correcta": "Imperio Romano", "incorrecta": ["Imperio Bizantino", "Imperio Griego", "Imperio Egipcio"]},
    {"pregunta": "¿Quién fue el líder del Imperio Francés durante las Guerras Napoleónicas?", "correcta": "Napoleón Bonaparte", "incorrecta": ["Luis XIV", "Carlos Martel", "Ricardo Corazón de León"]},
    {"pregunta": "¿Qué evento inició la Revolución Francesa?", "correcta": "La Toma de la Bastilla", "incorrecta": ["Asamblea Nacional", "Ejecución de Luis XVI", "Fin de la monarquía"]},
    {"pregunta": "¿Cuál fue el nombre del primer hombre en llegar a la Luna?", "correcta": "Neil Armstrong", "incorrecta": ["Buzz Aldrin", "Yuri Gagarin", "John Glenn"]},
    {"pregunta": "¿Cuál fue el conflicto bélico más largo del siglo XX?", "correcta": "Guerra de Vietnam", "incorrecta": ["Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra Fría"]},
    {"pregunta": "¿Qué rey inglés fue conocido como el Rey Sol?", "correcta": "Luis XIV", "incorrecta": ["Enrique VIII", "Carlos II", "Jorge I"]},
    {"pregunta": "¿Cuál es la civilización que construyó Machu Picchu?", "correcta": "Inca", "incorrecta": ["Azteca", "Maya", "Tolteca"]},
    {"pregunta": "¿En qué año se fundó la Organización de las Naciones Unidas?", "correcta": "1945", "incorrecta": ["1919", "1950", "1939"]},
    {"pregunta": "¿Quién fue el principal líder de la independencia de la India?", "correcta": "Mahatma Gandhi", "incorrecta": ["Jawaharlal Nehru", "Subhas Chandra Bose", "Indira Gandhi"]},
    {"pregunta": "¿En qué país se originó la democracia?", "correcta": "Grecia", "incorrecta": ["Roma", "Francia", "Alemania"]},
    {"pregunta": "¿Quién fue el presidente de los Estados Unidos durante la Guerra Civil?", "correcta": "Abraham Lincoln", "incorrecta": ["George Washington", "Thomas Jefferson", "Theodore Roosevelt"]},
    {"pregunta": "¿En qué país tuvo lugar la Revolución Rusa de 1917?", "correcta": "Rusia", "incorrecta": ["Francia", "Alemania", "Italia"]},
    {"pregunta": "¿Quién fue conocido como 'El Libertador' de América del Sur?", "correcta": "Simón Bolívar", "incorrecta": ["José de San Martín", "Bernardo O'Higgins", "Antonio José de Sucre"]},
    {"pregunta": "¿En qué siglo ocurrió la Revolución Industrial?", "correcta": "Siglo XIX", "incorrecta": ["Siglo XVIII", "Siglo XX", "Siglo XVII"]},
    {"pregunta": "¿Qué tratado puso fin a la Primera Guerra Mundial?", "correcta": "Tratado de Versalles", "incorrecta": ["Tratado de Tordesillas", "Tratado de París", "Tratado de Ginebra"]},
    {"pregunta": "¿Qué famoso general cruzó los Alpes con elefantes?", "correcta": "Aníbal", "incorrecta": ["Julio César", "Alejandro Magno", "Ciro el Grande"]}
]

entretenimiento = [
    {"pregunta": "¿Quién dirigió la película 'Titanic'?", "correcta": "James Cameron", "incorrecta": ["Steven Spielberg", "Martin Scorsese", "Christopher Nolan"]},
    {"pregunta": "¿Qué saga de películas incluye a Darth Vader?", "correcta": "Star Wars", "incorrecta": ["Star Trek", "Harry Potter", "El Señor de los Anillos"]},
    {"pregunta": "¿Quién es el creador de la serie 'Los Simpsons'?", "correcta": "Matt Groening", "incorrecta": ["Seth MacFarlane", "Trey Parker", "Vince Gilligan"]},
    {"pregunta": "¿Qué película ganó el Oscar a Mejor Película en 1994?", "correcta": "Forrest Gump", "incorrecta": ["Pulp Fiction", "El Rey León", "Cadena Perpetua"]},
    {"pregunta": "¿Cuál es el superhéroe que tiene una identidad secreta llamada Peter Parker?", "correcta": "Spider-Man", "incorrecta": ["Batman", "Superman", "Iron Man"]},
    {"pregunta": "¿Quién protagoniza la serie 'Breaking Bad'?", "correcta": "Bryan Cranston", "incorrecta": ["Aaron Paul", "Bob Odenkirk", "Dean Norris"]},
    {"pregunta": "¿Qué película animada tiene a un muñeco de madera que quiere ser un niño de verdad?", "correcta": "Pinocho", "incorrecta": ["Toy Story", "Shrek", "Frozen"]},
    {"pregunta": "¿Qué instrumento musical toca Lisa Simpson?", "correcta": "Saxofón", "incorrecta": ["Guitarra", "Piano", "Trompeta"]},
    {"pregunta": "¿Quién es el protagonista de la serie 'Sherlock' de la BBC?", "correcta": "Benedict Cumberbatch", "incorrecta": ["David Tennant", "Matt Smith", "Tom Hiddleston"]},
    {"pregunta": "¿Qué director es conocido por sus películas de terror como 'Psicosis'?", "correcta": "Alfred Hitchcock", "incorrecta": ["Stanley Kubrick", "John Carpenter", "Wes Craven"]},
    {"pregunta": "¿Qué saga de libros fue escrita por J.K. Rowling?", "correcta": "Harry Potter", "incorrecta": ["Percy Jackson", "Crepúsculo", "Los Juegos del Hambre"]},
    {"pregunta": "¿Quién interpreta a Jack Sparrow en la saga de 'Piratas del Caribe'?", "correcta": "Johnny Depp", "incorrecta": ["Orlando Bloom", "Hugh Jackman", "Robert Downey Jr."]},
    {"pregunta": "¿Qué película cuenta la historia de un joven mago que asiste a la escuela de Hogwarts?", "correcta": "Harry Potter", "incorrecta": ["Percy Jackson", "Las Crónicas de Narnia", "El Hobbit"]},
    {"pregunta": "¿Qué serie de televisión es conocida por la frase 'Winter is Coming'?", "correcta": "Game of Thrones", "incorrecta": ["Vikings", "The Witcher", "The Walking Dead"]},
    {"pregunta": "¿En qué ciudad está ambientada la serie 'Friends'?", "correcta": "Nueva York", "incorrecta": ["Los Ángeles", "Chicago", "Boston"]},
    {"pregunta": "¿Qué película animada de Pixar cuenta la historia de una familia de superhéroes?", "correcta": "Los Increíbles", "incorrecta": ["Toy Story", "Monsters, Inc.", "Buscando a Nemo"]},
    {"pregunta": "¿Cuál es el nombre del famoso arqueólogo protagonista de la saga 'Indiana Jones'?", "correcta": "Indiana Jones", "incorrecta": ["Allan Quatermain", "Rick O'Connell", "Nathan Drake"]},
    {"pregunta": "¿Qué serie de televisión tiene personajes llamados Sheldon, Leonard, y Penny?", "correcta": "The Big Bang Theory", "incorrecta": ["How I Met Your Mother", "Friends", "Parks and Recreation"]},
    {"pregunta": "¿Qué película de animación tiene a un niño llamado Simba?", "correcta": "El Rey León", "incorrecta": ["Bambi", "Dumbo", "Tarzán"]},
    {"pregunta": "¿Quién es el creador de la saga 'Juego de Tronos'?", "correcta": "George R.R. Martin", "incorrecta": ["J.R.R. Tolkien", "Patrick Rothfuss", "Brandon Sanderson"]}
]


ciencia = [
    {"pregunta": "¿Qué elemento químico tiene como símbolo 'O'?", "correcta": "Oxígeno", "incorrecta": ["Oro", "Osmio", "Ozono"]},
    {"pregunta": "¿Quién propuso la teoría de la relatividad?", "correcta": "Albert Einstein", "incorrecta": ["Isaac Newton", "Stephen Hawking", "Galileo Galilei"]},
    {"pregunta": "¿Qué planeta del sistema solar es el más cercano al Sol?", "correcta": "Mercurio", "incorrecta": ["Venus", "Marte", "Tierra"]},
    {"pregunta": "¿Cuál es la fórmula química del agua?", "correcta": "H2O", "incorrecta": ["CO2", "O2", "NaCl"]},
    {"pregunta": "¿Cuál es el animal más grande del mundo?", "correcta": "Ballena azul", "incorrecta": ["Elefante africano", "Tiburón blanco", "Jirafa"]},
    {"pregunta": "¿Qué gas es necesario para la respiración de los seres vivos?", "correcta": "Oxígeno", "incorrecta": ["Hidrógeno", "Nitrógeno", "Dióxido de carbono"]},
    {"pregunta": "¿Qué tipo de animal es una rana?", "correcta": "Anfibio", "incorrecta": ["Reptil", "Mamífero", "Ave"]},
    {"pregunta": "¿Qué científico desarrolló la teoría de la evolución?", "correcta": "Charles Darwin", "incorrecta": ["Gregor Mendel", "Marie Curie", "Louis Pasteur"]},
    {"pregunta": "¿Qué órgano humano produce la insulina?", "correcta": "Páncreas", "incorrecta": ["Hígado", "Riñón", "Estómago"]},
    {"pregunta": "¿Qué partícula subatómica tiene carga negativa?", "correcta": "Electrón", "incorrecta": ["Protón", "Neutrón", "Quark"]},
    {"pregunta": "¿Qué tipo de estrella es el Sol?", "correcta": "Enana amarilla", "incorrecta": ["Gigante roja", "Enana blanca", "Supernova"]},
    {"pregunta": "¿Qué hueso es el más largo del cuerpo humano?", "correcta": "Fémur", "incorrecta": ["Tibia", "Húmero", "Radio"]},
    {"pregunta": "¿Cuál es el planeta más grande del sistema solar?", "correcta": "Júpiter", "incorrecta": ["Saturno", "Urano", "Neptuno"]},
    {"pregunta": "¿Qué científico es famoso por sus leyes del movimiento?", "correcta": "Isaac Newton", "incorrecta": ["Galileo Galilei", "Albert Einstein", "Nikola Tesla"]},
    {"pregunta": "¿Qué animal pone huevos pero es un mamífero?", "correcta": "Ornitorrinco", "incorrecta": ["Canguro", "Murciélago", "Delfín"]},
    {"pregunta": "¿Qué gas se encuentra en mayor proporción en la atmósfera?", "correcta": "Nitrógeno", "incorrecta": ["Oxígeno", "Dióxido de carbono", "Hidrógeno"]},
    {"pregunta": "¿Qué planeta tiene un día más largo que su año?", "correcta": "Venus", "incorrecta": ["Mercurio", "Marte", "Neptuno"]},
    {"pregunta": "¿Qué rama de la ciencia estudia los fósiles?", "correcta": "Paleontología", "incorrecta": ["Geología", "Arqueología", "Biología"]},
    {"pregunta": "¿Qué científico descubrió la penicilina?", "correcta": "Alexander Fleming", "incorrecta": ["Louis Pasteur", "Marie Curie", "Isaac Newton"]},
    {"pregunta": "¿Qué tipo de sangre es considerado donante universal?", "correcta": "O negativo", "incorrecta": ["A positivo", "AB positivo", "B negativo"]}
]

actualidad = [
    {"pregunta": "¿En qué país ocurrió el Brexit?", "correcta": "Reino Unido", "incorrecta": ["Francia", "España", "Alemania"]},
    {"pregunta": "¿Cuál es el actual presidente de Rusia?", "correcta": "Vladimir Putin", "incorrecta": ["Dmitri Medvédev", "Boris Yeltsin", "Mijaíl Gorbachov"]},
    {"pregunta": "¿Qué país es conocido por tener el mayor Amazonas?", "correcta": "Brasil", "incorrecta": ["Colombia", "Perú", "Venezuela"]},
    {"pregunta": "¿Quién fue el presidente de los Estados Unidos en 2021?", "correcta": "Joe Biden", "incorrecta": ["Donald Trump", "Barack Obama", "George Bush"]},
    {"pregunta": "¿En qué año se celebró el Mundial de Fútbol en Rusia?", "correcta": "2018", "incorrecta": ["2014", "2016", "2020"]},
    {"pregunta": "¿Qué país tiene la mayor población del mundo?", "correcta": "China", "incorrecta": ["India", "Estados Unidos", "Indonesia"]},
    {"pregunta": "¿En qué año ocurrió la pandemia de COVID-19?", "correcta": "2020", "incorrecta": ["2019", "2018", "2021"]},
    {"pregunta": "¿Quién es el actual CEO de Tesla?", "correcta": "Elon Musk", "incorrecta": ["Jeff Bezos", "Tim Cook", "Bill Gates"]},
    {"pregunta": "¿Cuál es la red social más utilizada en 2021?", "correcta": "Facebook", "incorrecta": ["Twitter", "Instagram", "TikTok"]},
    {"pregunta": "¿En qué país se celebraron los Juegos Olímpicos de 2020 (celebrados en 2021)?", "correcta": "Japón", "incorrecta": ["China", "Brasil", "Australia"]},
    {"pregunta": "¿Qué empresa creó el sistema operativo Windows?", "correcta": "Microsoft", "incorrecta": ["Apple", "Google", "IBM"]},
    {"pregunta": "¿Qué país está asociado con el origen de la música K-pop?", "correcta": "Corea del Sur", "incorrecta": ["Japón", "China", "Tailandia"]},
    {"pregunta": "¿Quién es conocido por la fundación de Amazon?", "correcta": "Jeff Bezos", "incorrecta": ["Elon Musk", "Larry Page", "Steve Jobs"]},
    {"pregunta": "¿Qué vacuna contra el COVID-19 fue desarrollada por Pfizer?", "correcta": "Comirnaty", "incorrecta": ["AstraZeneca", "Moderna", "Sputnik V"]},
    {"pregunta": "¿Cuál es el valor aproximado de un bitcoin en 2021?", "correcta": "60,000 USD", "incorrecta": ["10,000 USD", "100,000 USD", "1,000 USD"]},
    {"pregunta": "¿Qué isla es conocida por el volcán Cumbre Vieja que hizo erupción en 2021?", "correcta": "La Palma", "incorrecta": ["Tenerife", "Gran Canaria", "Lanzarote"]},
    {"pregunta": "¿Qué plataforma de streaming lanzó la serie 'El Juego del Calamar'?", "correcta": "Netflix", "incorrecta": ["Amazon Prime", "HBO Max", "Disney+"]},
    {"pregunta": "¿Qué ciudad fue la sede de la cumbre del cambio climático COP26 en 2021?", "correcta": "Glasgow", "incorrecta": ["París", "Madrid", "Nueva York"]},
    {"pregunta": "¿Qué país anunció en 2021 su misión espacial para llegar a Marte en 2026?", "correcta": "China", "incorrecta": ["Rusia", "India", "Emiratos Árabes Unidos"]},
    {"pregunta": "¿Qué país es conocido por la producción masiva de semiconductores en 2021?", "correcta": "Taiwán", "incorrecta": ["Corea del Sur", "Japón", "Estados Unidos"]}
]
